### ISSUE TITLE
Please set VID and PID as constants and also export from the module

### ISSUE THREAD

**Issue by peternewman** [hopejr/ShuttleControlUSB#6]
Sorry I'm not really sure of the best/right syntax, so haven't done a PR, but if for example I want to show a picture of which device is connected (or in my case do remapping based on it, so extending/overloading your button info), I'd want to match based on something fixed per device type, name is the only thing currently available, but that feels rather brittle and would break if you e.g. decided to rename them as `ShuttlePro v2 or Multimedia Controller PRO v2` if they don't have different VID/PID combos for the new sales name.

If you created constants of say `VID_CONTOUR` and `PID_SHUTTLEPRO_V2` you could both use them in https://github.com/hopejr/ShuttleControlUSB/blob/master/lib/ShuttleDefs.js and also export them, then I could match based on those keys when deciding what to do (rather than duplicating the same info again in my code).

Having some sort of enum for the types/PIDs would be even better, something like this, but I don't know if it's the right JS version:
https://stackoverflow.com/questions/43000451/javascript-es6-enums-inside-classes-used-outside-like-a-static-enum

You might even want to have separate PID constants and type enums, in case they ever released different PIDs which were the same logical type, like the XKeys stuff does:
https://github.com/SuperFlyTV/xkeys/blob/master/packages/core/src/products.ts

**Comment by hopejr** [comment]
It seems that Object.freeze() would be the best way to do enums.

```
const vids = Object.freeze({
  CONTOUR: 0x0B33
})

const pids = Object.freeze({
  SHUTTLEPRO_V1: 0x0010,
  SHUTTLEXPRESS: 0x0020,
  SHUTTLEPRO_V2: 0x0030
})
```

Is this the sort of thing you're wanting?

**Comment by peternewman** [comment]
Yeah that's the idea. I assume I'll be able to import it and then do `pids.SHUTTLEPRO_V1` or something?

We shouldn't need multiple VIDs unless they buy another manufacturer...

I'm unclear how to combine that with your existing module export though:
https://github.com/hopejr/ShuttleControlUSB/blob/878063b38275220737abbee6b143c0c5cf91a9c0/index.js#L1

**Comment by hopejr** [comment]
I'll just expose it from Shuttle.js.

**Comment by peternewman** [comment]
Great thanks @hopejr . That's working nicely for me now!
