### ISSUE TITLE
Hotplug doesn't work

### ISSUE THREAD

**Issue by peternewman** [hopejr/ShuttleControlUSB#7]
At least in `npm run test`, if it's plugged in already, the tests run fine. Unplugging it at the end closing things, but if there's nothing plugged in and I run the tests, I only ever get:
```
> shuttle-control-usb@1.2.0 test
> node tests/test.js

Plug device in
```

This is on:
npm --version
9.5.1
node --version
v18.16.0
Linux 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux

**Comment by hopejr** [comment]
I've tested on macOS and Windows and it works there. Maybe it's a Linux thing? However, I know it used to work on Linux with usb-detection. I'll have to fire up my linux VM and test there.

**Comment by hopejr** [comment]
It turns out that there's a delay on Linux with hot plugging, just like on macOS. I only introduced a delay for macOS. I'll change it to happen on all platforms.
